Repository Simplon-hdf/reconditioned-gunslingers, pull requests merged in 2024-11, with the labels that each got.

#1 docs(doc): add file regles-de-gestion.md
  doc/regles-de-gestion.md
Labels: documentation

#2 docs(regle-de-gestion.md): add management rules
  doc/regles-de-gestion.md
Labels: documentation

#4 docs(doc): add dictionnaire-de-donnees file
  doc/dictionnaire-de-donnees.md
Labels: documentation

#6 docs(doc): update regles de gestion
  doc/regles-de-gestion.md
Labels: documentation

#7 docs(doc): change dictionnaire-de-donnees
  doc/dictionnaire-de-donnees.md
Labels: documentation

#9 docs(bdd/): init simpluedo database
  doc/bdd/bdd-init.sql
Labels: documentation

#10 docs(bdd/): update bdd-init.sql
  doc/bdd/bdd-init.sql
Labels: documentation

#11 feat(bdd/): add triggers in bdd-init.sql
  doc/bdd/bdd-init.sql
Labels: enhancement

#13 refactor(bdd/): change triggers and add table
  doc/bdd/bdd-init.sql
Labels: enhancement

#14 docs(bdd/): change dictionnary and add new save
  doc/bdd/dictionnaire-de-donnees.md
  doc/bdd/sauvegardes/simpluedo_backup.sql
Labels: documentation, enhancement

#15 feat(bdd/): add requetes.sql
  doc/bdd/bdd-init.sql
  doc/bdd/requetes.sql
Labels: enhancement

#16 docs(/): add readme content
  README.md
Labels: documentation

#18 docs(doc): rewrite correction-twins.md
  doc/correction-twins.md
Labels: documentation

#19 docs(doc): update correction-twins
  doc/correction-twins.md
Labels: documentation

#20 docs(doc): refactor correction-twins.md
  doc/correction-twins.md
Labels: documentation
